SELECT * FROM ANIMAL_INS order by ANIMAL_ID ASC
select NAME,DATETIME from ANIMAL_INS order by ANIMAL_ID DESC
select ANIMAL_ID, NAME from ANIMAL_INS where INTAKE_CONDITION = "sick" order by ANIMAL_ID;
select ANIMAL_ID, NAME from ANIMAL_INS where NOT INTAKE_CONDITION = "Aged" order by ANIMAL_ID asc;
SELECT ANIMAL_ID,NAME FROM ANIMAL_INS order by ANIMAL_ID ASC
select ANIMAL_ID,NAME,DATETIME from ANIMAL_INS order by NAME ASC, DATETIME DESC;
select ANIMAL_ID from ANIMAL_INS order by DATETIME ASC LIMIT 0,1